--from the 'Realistic Supply Replenishment' mod by Arcane Master--

NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 0.033	 
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.033
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 1.3	
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.068					
NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.035    	
NDefines.NMilitary.REINFORCEMENT_REQUEST_MAX_WAITING_DAYS = 70
NDefines.NMilitary.REINFORCEMENT_REQUEST_DAYS_FREQUENCY = 45   
NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 70
NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.65
NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.01
NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.06
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.8 
NDefines.STR_UNIT_WEAK = 0.25
NDefines.NAI.STR_UNIT_NORMAL = 0.5
NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 80
NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.65
NDefines.NAI.MIN_MANPOWER_TO_BUILD_UNITS = 0.65